/** Base nutricional importada da planilha oficial (valores médios por porção). */
export type BaseFood = {
  cat: string;
  name: string;
  portion: string;
  kcal: number;
  protein: number;
  carbs: number;
  fat: number;
};

export const FOOD_BASE: BaseFood[] = [
  { cat: "Proteínas", name: "Peito de frango grelhado", portion: "100 g", kcal: 165, protein: 31, carbs: 0, fat: 3.6 },
  { cat: "Proteínas", name: "Coxa de frango sem pele assada", portion: "100 g", kcal: 209, protein: 26, carbs: 0, fat: 10.9 },
  { cat: "Proteínas", name: "Patinho bovino grelhado", portion: "100 g", kcal: 219, protein: 32, carbs: 0, fat: 9.5 },
  { cat: "Proteínas", name: "Alcatra bovina grelhada", portion: "100 g", kcal: 250, protein: 29, carbs: 0, fat: 14 },
  { cat: "Proteínas", name: "Acém bovino cozido", portion: "100 g", kcal: 212, protein: 27, carbs: 0, fat: 11 },
  { cat: "Proteínas", name: "Músculo bovino cozido", portion: "100 g", kcal: 210, protein: 28, carbs: 0, fat: 10 },
  { cat: "Proteínas", name: "Filé mignon grelhado", portion: "100 g", kcal: 220, protein: 30, carbs: 0, fat: 10 },
  { cat: "Proteínas", name: "Carne moída magra", portion: "100 g", kcal: 220, protein: 27, carbs: 0, fat: 12 },
  { cat: "Proteínas", name: "Lombo suíno assado", portion: "100 g", kcal: 242, protein: 27, carbs: 0, fat: 14 },
  { cat: "Proteínas", name: "Filé suíno grelhado", portion: "100 g", kcal: 180, protein: 30, carbs: 0, fat: 6 },
  { cat: "Proteínas", name: "Peru assado sem pele", portion: "100 g", kcal: 170, protein: 29, carbs: 0, fat: 5 },
  { cat: "Proteínas", name: "Peito de peru fatiado", portion: "100 g", kcal: 105, protein: 18, carbs: 3, fat: 2 },
  { cat: "Proteínas", name: "Tilápia grelhada", portion: "100 g", kcal: 128, protein: 26, carbs: 0, fat: 2.7 },
  { cat: "Proteínas", name: "Salmão grelhado", portion: "100 g", kcal: 208, protein: 20, carbs: 0, fat: 13 },
  { cat: "Proteínas", name: "Atum em água", portion: "100 g", kcal: 116, protein: 26, carbs: 0, fat: 1 },
  { cat: "Proteínas", name: "Sardinha em água", portion: "100 g", kcal: 140, protein: 24, carbs: 0, fat: 4.5 },
  { cat: "Proteínas", name: "Merluza grelhada", portion: "100 g", kcal: 120, protein: 23, carbs: 0, fat: 2.5 },
  { cat: "Proteínas", name: "Bacalhau cozido dessalgado", portion: "100 g", kcal: 105, protein: 23, carbs: 0.9, fat: 0.8 },
  { cat: "Proteínas", name: "Camarão cozido", portion: "100 g", kcal: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  { cat: "Proteínas", name: "Ovo de galinha inteiro", portion: "1 un (50 g)", kcal: 72, protein: 6.3, carbs: 0.4, fat: 4.8 },
  { cat: "Proteínas", name: "Clara de ovo", portion: "3 claras (100 g)", kcal: 52, protein: 11, carbs: 0.7, fat: 0.2 },
  { cat: "Proteínas", name: "Omelete simples", portion: "2 ovos (100 g)", kcal: 144, protein: 12.6, carbs: 0.8, fat: 9.6 },
  { cat: "Proteínas", name: "Tofu firme", portion: "100 g", kcal: 144, protein: 17, carbs: 3, fat: 9 },
  { cat: "Proteínas", name: "Tempeh", portion: "100 g", kcal: 195, protein: 20, carbs: 8, fat: 11 },
  { cat: "Proteínas", name: "Proteína whey", portion: "30 g", kcal: 120, protein: 24, carbs: 3, fat: 2 },
  { cat: "Laticínios", name: "Leite integral", portion: "200 ml", kcal: 122, protein: 6.4, carbs: 9.4, fat: 6.6 },
  { cat: "Laticínios", name: "Leite semidesnatado", portion: "200 ml", kcal: 92, protein: 6.4, carbs: 9.6, fat: 3.2 },
  { cat: "Laticínios", name: "Leite desnatado", portion: "200 ml", kcal: 70, protein: 6.8, carbs: 10, fat: 0.2 },
  { cat: "Laticínios", name: "Iogurte natural integral", portion: "170 g", kcal: 105, protein: 5.5, carbs: 7, fat: 5.5 },
  { cat: "Laticínios", name: "Iogurte natural desnatado", portion: "170 g", kcal: 80, protein: 8.5, carbs: 10, fat: 0.5 },
  { cat: "Laticínios", name: "Iogurte grego natural", portion: "100 g", kcal: 97, protein: 9, carbs: 4, fat: 5 },
  { cat: "Laticínios", name: "Skyr natural", portion: "100 g", kcal: 63, protein: 11, carbs: 4, fat: 0.2 },
  { cat: "Laticínios", name: "Queijo minas frescal", portion: "30 g", kcal: 79, protein: 5.2, carbs: 0.9, fat: 6.1 },
  { cat: "Laticínios", name: "Muçarela", portion: "30 g", kcal: 90, protein: 6.6, carbs: 0.7, fat: 6.8 },
  { cat: "Laticínios", name: "Cottage", portion: "100 g", kcal: 98, protein: 11, carbs: 3.4, fat: 4.3 },
  { cat: "Laticínios", name: "Ricota", portion: "100 g", kcal: 140, protein: 12, carbs: 4, fat: 8 },
  { cat: "Laticínios", name: "Cream cheese", portion: "30 g", kcal: 100, protein: 2, carbs: 1.5, fat: 9.5 },
  { cat: "Laticínios", name: "Parmesão ralado", portion: "20 g", kcal: 86, protein: 7.6, carbs: 0.7, fat: 5.7 },
  { cat: "Cereais e pães", name: "Arroz branco cozido", portion: "100 g", kcal: 130, protein: 2.5, carbs: 28, fat: 0.3 },
  { cat: "Cereais e pães", name: "Arroz integral cozido", portion: "100 g", kcal: 123, protein: 2.7, carbs: 25.6, fat: 1 },
  { cat: "Cereais e pães", name: "Arroz parboilizado cozido", portion: "100 g", kcal: 123, protein: 2.9, carbs: 25.6, fat: 0.4 },
  { cat: "Cereais e pães", name: "Quinoa cozida", portion: "100 g", kcal: 120, protein: 4.4, carbs: 21.3, fat: 1.9 },
  { cat: "Cereais e pães", name: "Aveia em flocos", portion: "30 g", kcal: 114, protein: 3.9, carbs: 19.5, fat: 2.1 },
  { cat: "Cereais e pães", name: "Granola", portion: "30 g", kcal: 135, protein: 3, carbs: 22, fat: 4.2 },
  { cat: "Cereais e pães", name: "Pão francês", portion: "50 g", kcal: 135, protein: 4.5, carbs: 28, fat: 1 },
  { cat: "Cereais e pães", name: "Pão integral", portion: "50 g", kcal: 125, protein: 5, carbs: 23, fat: 2 },
  { cat: "Cereais e pães", name: "Pão de forma branco", portion: "50 g", kcal: 130, protein: 4, carbs: 25, fat: 1.5 },
  { cat: "Cereais e pães", name: "Pão de forma integral", portion: "50 g", kcal: 120, protein: 5, carbs: 21, fat: 2 },
  { cat: "Cereais e pães", name: "Tapioca pronta", portion: "50 g", kcal: 130, protein: 0, carbs: 32, fat: 0 },
  { cat: "Cereais e pães", name: "Cuscuz de milho cozido", portion: "100 g", kcal: 112, protein: 2.2, carbs: 25, fat: 0.5 },
  { cat: "Cereais e pães", name: "Polenta cozida", portion: "100 g", kcal: 70, protein: 1.5, carbs: 15, fat: 0.2 },
  { cat: "Cereais e pães", name: "Macarrão cozido", portion: "100 g", kcal: 158, protein: 5.8, carbs: 30.9, fat: 0.9 },
  { cat: "Cereais e pães", name: "Macarrão integral cozido", portion: "100 g", kcal: 149, protein: 5.5, carbs: 28, fat: 1.3 },
  { cat: "Cereais e pães", name: "Batata inglesa cozida", portion: "100 g", kcal: 87, protein: 1.9, carbs: 20, fat: 0.1 },
  { cat: "Cereais e pães", name: "Batata-doce cozida", portion: "100 g", kcal: 86, protein: 1.6, carbs: 20, fat: 0.1 },
  { cat: "Cereais e pães", name: "Mandioca cozida", portion: "100 g", kcal: 125, protein: 1, carbs: 30, fat: 0.3 },
  { cat: "Cereais e pães", name: "Inhame cozido", portion: "100 g", kcal: 118, protein: 1.5, carbs: 28, fat: 0.2 },
  { cat: "Cereais e pães", name: "Mandioquinha cozida", portion: "100 g", kcal: 80, protein: 1, carbs: 19, fat: 0.2 },
  { cat: "Cereais e pães", name: "Milho cozido", portion: "100 g", kcal: 96, protein: 3.4, carbs: 21, fat: 1.5 },
  { cat: "Cereais e pães", name: "Pipoca sem óleo", portion: "20 g", kcal: 75, protein: 2.5, carbs: 15, fat: 1 },
  { cat: "Leguminosas", name: "Feijão carioca cozido", portion: "100 g", kcal: 76, protein: 4.8, carbs: 13.6, fat: 0.5 },
  { cat: "Leguminosas", name: "Feijão preto cozido", portion: "100 g", kcal: 77, protein: 4.5, carbs: 14, fat: 0.5 },
  { cat: "Leguminosas", name: "Lentilha cozida", portion: "100 g", kcal: 116, protein: 9, carbs: 20, fat: 0.4 },
  { cat: "Leguminosas", name: "Grão-de-bico cozido", portion: "100 g", kcal: 164, protein: 8.9, carbs: 27.4, fat: 2.6 },
  { cat: "Leguminosas", name: "Ervilha cozida", portion: "100 g", kcal: 84, protein: 5.4, carbs: 15, fat: 0.4 },
  { cat: "Leguminosas", name: "Soja cozida", portion: "100 g", kcal: 173, protein: 17.3, carbs: 9.9, fat: 9 },
  { cat: "Frutas", name: "Banana prata", portion: "1 un média (80 g)", kcal: 72, protein: 0.9, carbs: 19, fat: 0.2 },
  { cat: "Frutas", name: "Banana nanica", portion: "1 un média (90 g)", kcal: 80, protein: 1, carbs: 21, fat: 0.2 },
  { cat: "Frutas", name: "Maçã com casca", portion: "1 un média (130 g)", kcal: 68, protein: 0.3, carbs: 18, fat: 0.2 },
  { cat: "Frutas", name: "Pera", portion: "1 un média (150 g)", kcal: 86, protein: 0.5, carbs: 23, fat: 0.2 },
  { cat: "Frutas", name: "Laranja", portion: "1 un média (130 g)", kcal: 61, protein: 1.2, carbs: 15, fat: 0.2 },
  { cat: "Frutas", name: "Tangerina", portion: "1 un média (100 g)", kcal: 53, protein: 0.8, carbs: 13, fat: 0.3 },
  { cat: "Frutas", name: "Mamão", portion: "150 g", kcal: 65, protein: 1, carbs: 16, fat: 0.4 },
  { cat: "Frutas", name: "Manga", portion: "100 g", kcal: 60, protein: 0.8, carbs: 15, fat: 0.4 },
  { cat: "Frutas", name: "Abacaxi", portion: "100 g", kcal: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { cat: "Frutas", name: "Melancia", portion: "200 g", kcal: 60, protein: 1.2, carbs: 15, fat: 0.3 },
  { cat: "Frutas", name: "Melão", portion: "150 g", kcal: 51, protein: 1.2, carbs: 12, fat: 0.3 },
  { cat: "Frutas", name: "Morango", portion: "100 g", kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3 },
  { cat: "Frutas", name: "Uva", portion: "100 g", kcal: 69, protein: 0.7, carbs: 18, fat: 0.2 },
  { cat: "Frutas", name: "Kiwi", portion: "100 g", kcal: 61, protein: 1.1, carbs: 15, fat: 0.5 },
  { cat: "Frutas", name: "Abacate", portion: "100 g", kcal: 160, protein: 2, carbs: 8.5, fat: 14.7 },
  { cat: "Frutas", name: "Goiaba", portion: "100 g", kcal: 68, protein: 2.6, carbs: 14, fat: 1 },
  { cat: "Frutas", name: "Maracujá polpa", portion: "100 g", kcal: 97, protein: 2.2, carbs: 23, fat: 0.7 },
  { cat: "Frutas", name: "Pêssego", portion: "100 g", kcal: 39, protein: 0.9, carbs: 9.5, fat: 0.3 },
  { cat: "Frutas", name: "Ameixa", portion: "100 g", kcal: 46, protein: 0.7, carbs: 11.4, fat: 0.3 },
  { cat: "Frutas", name: "Coco fresco", portion: "50 g", kcal: 177, protein: 1.7, carbs: 7.1, fat: 17 },
  { cat: "Verduras e legumes", name: "Alface", portion: "100 g", kcal: 15, protein: 1.4, carbs: 2.9, fat: 0.2 },
  { cat: "Verduras e legumes", name: "Rúcula", portion: "100 g", kcal: 25, protein: 2.6, carbs: 3.7, fat: 0.7 },
  { cat: "Verduras e legumes", name: "Couve", portion: "100 g", kcal: 49, protein: 4.3, carbs: 8.8, fat: 0.9 },
  { cat: "Verduras e legumes", name: "Espinafre", portion: "100 g", kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { cat: "Verduras e legumes", name: "Brócolis cozido", portion: "100 g", kcal: 35, protein: 2.4, carbs: 7.2, fat: 0.4 },
  { cat: "Verduras e legumes", name: "Couve-flor cozida", portion: "100 g", kcal: 23, protein: 1.8, carbs: 4.1, fat: 0.5 },
  { cat: "Verduras e legumes", name: "Cenoura cozida", portion: "100 g", kcal: 35, protein: 0.8, carbs: 8.2, fat: 0.2 },
  { cat: "Verduras e legumes", name: "Abobrinha cozida", portion: "100 g", kcal: 17, protein: 1.2, carbs: 3.1, fat: 0.3 },
  { cat: "Verduras e legumes", name: "Berinjela cozida", portion: "100 g", kcal: 35, protein: 0.8, carbs: 8.7, fat: 0.2 },
  { cat: "Verduras e legumes", name: "Tomate", portion: "100 g", kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { cat: "Verduras e legumes", name: "Pepino", portion: "100 g", kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  { cat: "Verduras e legumes", name: "Beterraba cozida", portion: "100 g", kcal: 44, protein: 1.7, carbs: 10, fat: 0.2 },
  { cat: "Verduras e legumes", name: "Vagem cozida", portion: "100 g", kcal: 35, protein: 1.9, carbs: 7.9, fat: 0.3 },
  { cat: "Verduras e legumes", name: "Abóbora cabotiá cozida", portion: "100 g", kcal: 48, protein: 1.4, carbs: 10.8, fat: 0.7 },
  { cat: "Verduras e legumes", name: "Pimentão vermelho", portion: "100 g", kcal: 31, protein: 1, carbs: 6, fat: 0.3 },
  { cat: "Verduras e legumes", name: "Cebola", portion: "100 g", kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1 },
  { cat: "Verduras e legumes", name: "Alho", portion: "10 g", kcal: 15, protein: 0.6, carbs: 3.3, fat: 0.1 },
  { cat: "Verduras e legumes", name: "Chuchu cozido", portion: "100 g", kcal: 19, protein: 0.8, carbs: 4.5, fat: 0.1 },
  { cat: "Oleaginosas e sementes", name: "Amendoim torrado", portion: "30 g", kcal: 170, protein: 7.7, carbs: 5.1, fat: 14.7 },
  { cat: "Oleaginosas e sementes", name: "Pasta de amendoim", portion: "20 g", kcal: 118, protein: 5, carbs: 4, fat: 10 },
  { cat: "Oleaginosas e sementes", name: "Castanha-do-pará", portion: "20 g", kcal: 132, protein: 2.9, carbs: 2.4, fat: 13.3 },
  { cat: "Oleaginosas e sementes", name: "Castanha de caju", portion: "30 g", kcal: 166, protein: 5.5, carbs: 9, fat: 13.2 },
  { cat: "Oleaginosas e sementes", name: "Amêndoas", portion: "30 g", kcal: 174, protein: 6.4, carbs: 6.5, fat: 15 },
  { cat: "Oleaginosas e sementes", name: "Nozes", portion: "30 g", kcal: 196, protein: 4.6, carbs: 4.1, fat: 19.6 },
  { cat: "Oleaginosas e sementes", name: "Pistache", portion: "30 g", kcal: 169, protein: 6.1, carbs: 8.5, fat: 13.5 },
  { cat: "Oleaginosas e sementes", name: "Chia", portion: "15 g", kcal: 73, protein: 2.5, carbs: 6.3, fat: 4.6 },
  { cat: "Oleaginosas e sementes", name: "Linhaça", portion: "15 g", kcal: 80, protein: 2.7, carbs: 4.3, fat: 6.3 },
  { cat: "Oleaginosas e sementes", name: "Semente de abóbora", portion: "30 g", kcal: 168, protein: 9, carbs: 4.2, fat: 14.7 },
  { cat: "Oleaginosas e sementes", name: "Gergelim", portion: "20 g", kcal: 115, protein: 3.5, carbs: 4.7, fat: 10 },
  { cat: "Bebidas", name: "Água", portion: "250 ml", kcal: 0, protein: 0, carbs: 0, fat: 0 },
  { cat: "Bebidas", name: "Água de coco", portion: "200 ml", kcal: 38, protein: 0.7, carbs: 9, fat: 0.2 },
  { cat: "Bebidas", name: "Café preto sem açúcar", portion: "200 ml", kcal: 2, protein: 0.3, carbs: 0, fat: 0 },
  { cat: "Bebidas", name: "Chá verde sem açúcar", portion: "200 ml", kcal: 1, protein: 0, carbs: 0.2, fat: 0 },
  { cat: "Bebidas", name: "Chá de camomila sem açúcar", portion: "200 ml", kcal: 2, protein: 0, carbs: 0.5, fat: 0 },
  { cat: "Bebidas", name: "Leite com café sem açúcar", portion: "200 ml", kcal: 75, protein: 4.5, carbs: 7, fat: 3 },
  { cat: "Bebidas", name: "Suco de laranja natural", portion: "200 ml", kcal: 90, protein: 1.4, carbs: 21, fat: 0.2 },
  { cat: "Bebidas", name: "Suco de limão natural sem açúcar", portion: "200 ml", kcal: 18, protein: 0.7, carbs: 6, fat: 0.2 },
  { cat: "Bebidas", name: "Suco de maracujá natural sem açúcar", portion: "200 ml", kcal: 55, protein: 1, carbs: 13, fat: 0.4 },
  { cat: "Bebidas", name: "Suco de abacaxi natural sem açúcar", portion: "200 ml", kcal: 90, protein: 0.7, carbs: 22, fat: 0.2 },
  { cat: "Bebidas", name: "Suco de uva integral", portion: "200 ml", kcal: 120, protein: 0.8, carbs: 29, fat: 0.2 },
  { cat: "Bebidas", name: "Refrigerante comum", portion: "350 ml", kcal: 147, protein: 0, carbs: 37, fat: 0 },
  { cat: "Bebidas", name: "Refrigerante zero", portion: "350 ml", kcal: 0, protein: 0, carbs: 0, fat: 0 },
  { cat: "Bebidas", name: "Bebida esportiva isotônica", portion: "500 ml", kcal: 120, protein: 0, carbs: 30, fat: 0 },
  { cat: "Bebidas", name: "Bebida energética", portion: "250 ml", kcal: 110, protein: 0, carbs: 27, fat: 0 },
  { cat: "Bebidas", name: "Água com gás", portion: "350 ml", kcal: 0, protein: 0, carbs: 0, fat: 0 },
  { cat: "Café da manhã e lanches", name: "Tapioca com ovo", portion: "1 porção", kcal: 202, protein: 6.3, carbs: 32.4, fat: 5 },
  { cat: "Café da manhã e lanches", name: "Pão integral com ovo", portion: "1 sanduíche", kcal: 197, protein: 11.3, carbs: 23, fat: 7 },
  { cat: "Café da manhã e lanches", name: "Aveia com banana e leite", portion: "1 tigela", kcal: 300, protein: 11, carbs: 47, fat: 8 },
  { cat: "Café da manhã e lanches", name: "Iogurte com aveia e morango", portion: "1 tigela", kcal: 230, protein: 13, carbs: 30, fat: 6 },
  { cat: "Café da manhã e lanches", name: "Vitamina de banana com leite", portion: "300 ml", kcal: 220, protein: 9, carbs: 36, fat: 6 },
  { cat: "Café da manhã e lanches", name: "Vitamina de mamão com leite", portion: "300 ml", kcal: 190, protein: 9, carbs: 29, fat: 5 },
  { cat: "Café da manhã e lanches", name: "Overnight oats com iogurte", portion: "1 pote", kcal: 280, protein: 15, carbs: 39, fat: 7 },
  { cat: "Café da manhã e lanches", name: "Crepioca com frango", portion: "1 porção", kcal: 290, protein: 28, carbs: 24, fat: 8 },
  { cat: "Café da manhã e lanches", name: "Cuscuz com ovo", portion: "1 porção", kcal: 250, protein: 10, carbs: 36, fat: 7 },
  { cat: "Café da manhã e lanches", name: "Pão francês com queijo minas", portion: "1 unidade", kcal: 220, protein: 10, carbs: 30, fat: 7 },
  { cat: "Café da manhã e lanches", name: "Iogurte proteico", portion: "1 unidade (160 g)", kcal: 120, protein: 15, carbs: 10, fat: 2 },
  { cat: "Café da manhã e lanches", name: "Whey com água", portion: "30 g", kcal: 120, protein: 24, carbs: 3, fat: 2 },
  { cat: "Café da manhã e lanches", name: "Banana com pasta de amendoim", portion: "1 banana + 15 g", kcal: 160, protein: 4, carbs: 23, fat: 6 },
  { cat: "Café da manhã e lanches", name: "Maçã com pasta de amendoim", portion: "1 maçã + 15 g", kcal: 155, protein: 4, carbs: 22, fat: 6 },
  { cat: "Pratos e refeições", name: "Arroz + feijão + frango", portion: "1 prato", kcal: 520, protein: 42, carbs: 62, fat: 10 },
  { cat: "Pratos e refeições", name: "Arroz + feijão + carne magra", portion: "1 prato", kcal: 570, protein: 39, carbs: 61, fat: 17 },
  { cat: "Pratos e refeições", name: "Arroz + feijão + peixe", portion: "1 prato", kcal: 500, protein: 37, carbs: 61, fat: 10 },
  { cat: "Pratos e refeições", name: "Arroz integral + frango + legumes", portion: "1 prato", kcal: 480, protein: 43, carbs: 53, fat: 10 },
  { cat: "Pratos e refeições", name: "Macarrão + carne moída magra", portion: "1 prato", kcal: 560, protein: 36, carbs: 62, fat: 18 },
  { cat: "Pratos e refeições", name: "Batata-doce + frango + salada", portion: "1 prato", kcal: 450, protein: 43, carbs: 48, fat: 9 },
  { cat: "Pratos e refeições", name: "Mandioca + carne magra + salada", portion: "1 prato", kcal: 520, protein: 37, carbs: 52, fat: 17 },
  { cat: "Pratos e refeições", name: "Omelete com legumes", portion: "1 prato", kcal: 280, protein: 20, carbs: 12, fat: 17 },
  { cat: "Pratos e refeições", name: "Salada completa com frango", portion: "1 prato", kcal: 360, protein: 38, carbs: 18, fat: 15 },
  { cat: "Pratos e refeições", name: "Salada completa com atum", portion: "1 prato", kcal: 320, protein: 35, carbs: 18, fat: 12 },
  { cat: "Pratos e refeições", name: "Bowl de quinoa, frango e legumes", portion: "1 bowl", kcal: 500, protein: 42, carbs: 52, fat: 13 },
  { cat: "Pratos e refeições", name: "Bowl de grão-de-bico e legumes", portion: "1 bowl", kcal: 430, protein: 17, carbs: 57, fat: 14 },
  { cat: "Pratos e refeições", name: "Sopa de legumes com frango", portion: "400 ml", kcal: 300, protein: 30, carbs: 27, fat: 8 },
  { cat: "Pratos e refeições", name: "Sopa de lentilha", portion: "400 ml", kcal: 300, protein: 18, carbs: 44, fat: 5 },
  { cat: "Pratos e refeições", name: "Panqueca de banana e aveia", portion: "2 unidades", kcal: 280, protein: 9, carbs: 45, fat: 7 },
  { cat: "Pratos e refeições", name: "Panqueca de frango e aveia", portion: "2 unidades", kcal: 330, protein: 31, carbs: 28, fat: 10 },
  { cat: "Doces e extras", name: "Chocolate 70% cacau", portion: "20 g", kcal: 120, protein: 1.6, carbs: 7, fat: 9 },
  { cat: "Doces e extras", name: "Chocolate ao leite", portion: "20 g", kcal: 107, protein: 1.5, carbs: 12, fat: 6 },
  { cat: "Doces e extras", name: "Mel", portion: "15 g", kcal: 46, protein: 0, carbs: 12.5, fat: 0 },
  { cat: "Doces e extras", name: "Geleia de frutas", portion: "20 g", kcal: 50, protein: 0, carbs: 13, fat: 0 },
  { cat: "Doces e extras", name: "Pasta de amendoim sem açúcar", portion: "20 g", kcal: 118, protein: 5, carbs: 4, fat: 10 },
  { cat: "Doces e extras", name: "Geleia diet", portion: "20 g", kcal: 15, protein: 0, carbs: 4, fat: 0 },
  { cat: "Doces e extras", name: "Gelatina diet", portion: "120 g", kcal: 10, protein: 1.5, carbs: 0, fat: 0 },
  { cat: "Doces e extras", name: "Gelatina comum", portion: "120 g", kcal: 80, protein: 2, carbs: 18, fat: 0 },
];

export const FOOD_CATEGORIES = Array.from(new Set(FOOD_BASE.map((f) => f.cat)));
