/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreinosRouteImport } from './routes/treinos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as EvolucaoRouteImport } from './routes/evolucao'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as IndexRouteImport } from './routes/index'

const TreinosRoute = TreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucaoRoute = EvolucaoRouteImport.update({
  id: '/evolucao',
  path: '/evolucao',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/desafios': typeof DesafiosRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/treinos': typeof TreinosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/desafios': typeof DesafiosRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/treinos': typeof TreinosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dashboard': typeof DashboardRoute
  '/desafios': typeof DesafiosRoute
  '/dieta': typeof DietaRoute
  '/evolucao': typeof EvolucaoRoute
  '/relatorios': typeof RelatoriosRoute
  '/treinos': typeof TreinosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/dashboard'
    | '/desafios'
    | '/dieta'
    | '/evolucao'
    | '/relatorios'
    | '/treinos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/dashboard'
    | '/desafios'
    | '/dieta'
    | '/evolucao'
    | '/relatorios'
    | '/treinos'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/configuracoes'
    | '/dashboard'
    | '/desafios'
    | '/dieta'
    | '/evolucao'
    | '/relatorios'
    | '/treinos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DashboardRoute: typeof DashboardRoute
  DesafiosRoute: typeof DesafiosRoute
  DietaRoute: typeof DietaRoute
  EvolucaoRoute: typeof EvolucaoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TreinosRoute: typeof TreinosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treinos': {
      id: '/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof TreinosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucao': {
      id: '/evolucao'
      path: '/evolucao'
      fullPath: '/evolucao'
      preLoaderRoute: typeof EvolucaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DashboardRoute: DashboardRoute,
  DesafiosRoute: DesafiosRoute,
  DietaRoute: DietaRoute,
  EvolucaoRoute: EvolucaoRoute,
  RelatoriosRoute: RelatoriosRoute,
  TreinosRoute: TreinosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
